# Arquivo: gradle/libs.versions.toml

[versions]
# AndroidX e Material
coreKtx = "1.16.0"
appcompat = "1.7.1"
material = "1.12.0"
activityKtx = "1.10.1"
constraintlayout = "2.2.1"
gridlayout = "1.1.0"
preferenceKtx = "1.2.1"
documentfile = "1.1.0"
lifecycle = "2.9.2"
workRuntimeKtx = "2.10.2"

# Kotlin Coroutines
coroutines = "1.10.2"

# Google Services
playServicesAds = "24.4.0"
guava = "33.4.8-android"

# Testes
junit = "4.13.2"
androidxJunit = "1.2.1"
espressoCore = "3.6.1"

# Plugins
androidApplication = "8.11.1"
kotlinAndroid = "2.2.0"

[libraries]
# AndroidX e Material
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "gridlayout" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }

# Kotlin Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Google Services
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "playServicesAds" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

# Testes
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplication" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid" }